"""
Aegis CLI — Command-line interface for the safety gateway.

Usage::

    aegis serve                 # Start the server
    aegis serve --port 9000     # Custom port
    aegis init-config           # Generate a .env config file
    aegis health                # Check server health
    aegis generate-key admin    # Generate an API key
    aegis generate-fernet-key   # Generate a Fernet encryption key
"""

from __future__ import annotations

import argparse
import sys


def cmd_serve(args):
    """Start the Aegis server."""
    import uvicorn

    # NOTE: Uvicorn requires an import string (module:app) when reload/workers
    # are enabled. Passing an app instance emits a warning.
    uvicorn.run(
        "aegis.server:app",
        host=args.host or "0.0.0.0",
        port=args.port or 8000,
        reload=args.debug,
        workers=1 if args.debug else (args.workers or 4),
        log_level="debug" if args.debug else "info",
        factory=False,
    )


def cmd_init_config(args):
    """Generate a .env configuration file."""
    config = """# Aegis Configuration
# Generated by: aegis init-config

# ========== APPLICATION ==========
ASG_APP_NAME=Aegis
ASG_ENVIRONMENT=development
ASG_DEBUG=true

# ========== SERVER ==========
ASG_HOST=0.0.0.0
ASG_PORT=8000
ASG_WORKERS=4

# ========== CORS & SECURITY ==========
ASG_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
ASG_REQUIRE_HTTPS=false

# ========== AUTHENTICATION ==========
# Set to true and configure API keys for production
ASG_REQUIRE_AUTH=false
# Format: role:key,role:key (e.g. admin:mykey123,agent:agentkey456)
# ASG_API_KEYS=

# ========== STORAGE ==========
ASG_SQLITE_PATH=data/gateway.db
ASG_LOG_DIR=logs
ASG_BACKUP_DIR=data/backups

# ========== SAFETY POLICY ==========
ASG_STRICT_BLOCK_DELETE_PRODUCTION=true
ASG_RISK_THRESHOLD_APPROVAL=70
ASG_REQUIRE_AGENT_REGISTRATION=false

# ========== AUDIT ==========
ASG_AUDIT_PAYLOAD_MODE=full
ASG_LOG_LEVEL=INFO
ASG_LOG_FORMAT=json

# ========== ENCRYPTION (optional) ==========
# Generate: aegis generate-fernet-key
# ASG_FERNET_KEY=
ASG_ENCRYPT_BACKUP_FILES=false

# ========== RATE LIMITING ==========
ASG_RATE_LIMIT_ACTIONS_PER_MINUTE=100
"""
    if args.output:
        with open(args.output, "w") as f:
            f.write(config)
        print(f"✅ Config written to {args.output}")
    else:
        print(config)


def cmd_health(args):
    """Check server health."""
    try:
        import httpx

        url = args.url or "http://localhost:8000"
        r = httpx.get(f"{url}/health", timeout=5)
        data = r.json()
        print(f"✅ {data.get('service', 'Aegis')} v{data.get('version', '?')}")
        print(f"   Status:      {data.get('status', '?')}")
        print(f"   Environment: {data.get('environment', '?')}")

        # Also check readiness
        r2 = httpx.get(f"{url}/health/ready", timeout=5)
        d2 = r2.json()
        print(f"   Ready:       {d2.get('status', '?')}")
    except Exception as e:
        print(f"❌ Cannot reach server: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_generate_key(args):
    """Generate an API key."""
    from aegis.core.auth import generate_api_key

    role = args.role or "admin"
    raw_key, key_hash = generate_api_key(role)
    print(f"🔑 Generated API key (role: {role})")
    print(f"   Key:  {raw_key}")
    print(f"   Hash: {key_hash}")
    print()
    print(f"Add to .env: ASG_API_KEYS={role}:{raw_key}")
    print("⚠️  Store the key securely — it cannot be recovered.")


def cmd_generate_fernet_key(args):
    """Generate a Fernet encryption key."""
    try:
        from cryptography.fernet import Fernet

        key = Fernet.generate_key().decode()
        print(f"🔐 Fernet key: {key}")
        print(f"\nAdd to .env: ASG_FERNET_KEY={key}")
    except ImportError:
        print(
            "❌ cryptography package not installed. Run: pip install cryptography",
            file=sys.stderr,
        )
        sys.exit(1)


def main():
    """Aegis CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="aegis",
        description="Aegis — AI Safety Gateway CLI",
    )
    parser.add_argument(
        "--version",
        action="version",
        version="%(prog)s 2.0.0",
    )

    subparsers = parser.add_subparsers(dest="command", help="Commands")

    # serve
    serve_parser = subparsers.add_parser(
        "serve", help="Start the Aegis server"
    )
    serve_parser.add_argument(
        "--host", default="0.0.0.0", help="Bind host"
    )
    serve_parser.add_argument(
        "--port", type=int, default=8000, help="Bind port"
    )
    serve_parser.add_argument(
        "--workers", type=int, default=4, help="Number of workers"
    )
    serve_parser.add_argument(
        "--debug", action="store_true", help="Enable debug mode"
    )

    # init-config
    init_parser = subparsers.add_parser(
        "init-config", help="Generate a .env config file"
    )
    init_parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output file path (default: stdout)",
    )

    # health
    health_parser = subparsers.add_parser(
        "health", help="Check server health"
    )
    health_parser.add_argument(
        "--url",
        default="http://localhost:8000",
        help="Server URL",
    )

    # generate-key
    key_parser = subparsers.add_parser(
        "generate-key", help="Generate an API key"
    )
    key_parser.add_argument(
        "role",
        nargs="?",
        default="admin",
        choices=["admin", "operator", "agent"],
        help="Key role",
    )

    # generate-fernet-key
    subparsers.add_parser(
        "generate-fernet-key",
        help="Generate a Fernet encryption key",
    )

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    commands = {
        "serve": cmd_serve,
        "init-config": cmd_init_config,
        "health": cmd_health,
        "generate-key": cmd_generate_key,
        "generate-fernet-key": cmd_generate_fernet_key,
    }

    cmd = commands.get(args.command)
    if cmd:
        cmd(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
